# Manually handle submodules
git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - rm -rf public || exit 0
  - mkdir ~/_bin
  - wget https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.tar.gz -O hugo.tgz
  - tar xfv hugo.tgz -C ~/_bin
  - rm hugo.tgz ~/_bin/*.md
  - export PATH=$HOME/_bin:$PATH

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "/public"
  target_branch: master
  on:
    branch: source
