baseurl = "https://hizkifw.github.io/"
languageCode = "en-us"
title = "HizkiFW's blog"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-69610279-5"
disqusShortname = "hizkiblog"
enableEmoji = true

[params]
    name = "Hizkia Felix"
    description = "Just a blog"
    bio = "I'm a human. I think."
    # Enter optionally your twitter account
    twitter = "HizkiFW"
    enableRSS = true

    # Integrate Javascript files or stylesheets by adding the url to the external assets or by
    # linking local files with their path relative to the static folder, e.g. "css/styles.css"
    customCSS = ["css/blog.css"]
    customJS  = ["js/twemoji.min.js?2.4", "js/blog.js"]

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = ""
    subscribe = ""
    # Pagination links
    olderPosts = ""
    newerPosts = ""
    readMore = ""
    copyright = "[![Work licensed under CC BY NC SA](/images/by-nc-sa.svg)](http://creativecommons.org/licenses/by-nc-sa/4.0/)"
    # Sharing options and author information in posts
    aboutAuthor = "I'm a human. Probably."
    tweet = ""
    share = ""
    # 404 page
    title404 = "404"
    subtitle404 = "Page not found"

    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
    iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

[social]
    twitter = "https://www.twitter.com/hizkifw"
    githubalt = "https://www.github.com/hizkifw"
    email = "mailto:hizkifw@gmail.com"
    youtube = "https://www.youtube.com/c/HizkiFWOfficial"
    reddit = "https://reddit.com/u/HizkiFW"
